kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: git-operator
subjects:
- kind: ServiceAccount
  name: git-operator
  namespace: devconsole-git
roleRef:
  kind: ClusterRole
  name: git-operator
  apiGroup: rbac.authorization.k8s.io
